package me.zavdav.zcore.internal.exception

internal class UserNotFoundException(val name: String) : RuntimeException()